name: Python architecture

on:
  push:
    branches: [main]
  pull_request:

jobs:
  x86-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-alpine
        options: --platform=linux/386
    steps:
      - name: Run on i386 docker
        run: |
          import sys
          import struct
          print('pointer size: {:d}'.format(struct.calcsize('P') * 8))
          print(f'sys.maxsize: {sys.maxsize}')
        shell: python
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        exclude:
        - os: macos-latest
          python-version: 3.7
        - os: macos-latest
          python-version: 3.9
        - os: macos-latest
          python-version: pypy3
        - os: windows-latest
          python-version: 3.7
        - os: windows-latest
          python-version: 3.9
        - os: windows-latest
          python-version: pypy3  # https://github.com/python-trio/trio/issues/1361
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run test script
      run: python test_architecture.py
